# This file is used to define the workflow for Flutter mobile app

name: Flutter

on:
  push:
    branches:
      - main
    paths:
      - 'mobile/**'
  pull_request:
    branches:
      - main
    paths:
      - 'mobile/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: stable

      - name: Install dependencies
        working-directory: mobile
        run: flutter pub get

      - name: Run tests
        working-directory: mobile
        run: flutter test
